pipeline {
    agent any

    tools {
        jdk 'jdk17'
        maven 'maven'
    }

    stages {

        stage('Checkout Code') {
            steps {
                git url: 'https://github.com/nikhilpatill/CI_CD_playwrite_execution.git', branch: 'main'
            }
        }

        stage('Check Java Version') {
            steps {
                bat 'java -version'
            }
        }

        stage('Build') {
            steps {
                dir('Playwright-Java-PageObjectModel-master') {
                    bat 'mvn clean package -Dmaven.test.failure.ignore=true'
                }
            }
            post {
                success {
                    junit 'Playwright-Java-PageObjectModel-master/target/surefire-reports/TEST-*.xml'
                    archiveArtifacts 'Playwright-Java-PageObjectModel-master/target/*.jar'
                }
            }
        }

        stage("Deploy to QA") {
            steps {
                echo "Deploying to QA..."
            }
        }

        stage('Regression Automation Test') {
            steps {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    dir('Playwright-Java-PageObjectModel-master') {
                        bat 'mvn clean test -Dsurefire.suiteXmlFiles=src/test/resources/testrunners/testng_regressions.xml'
                    }
                }
            }
        }

        stage('Publish Extent Report') {
            steps {
                publishHTML([
                    allowMissing: false,
                    alwaysLinkToLastBuild: false,
                    keepAll: true,
                    reportDir: 'Playwright-Java-PageObjectModel-master/build',
                    reportFiles: 'TestExecutionReport.html',
                    reportName: 'HTML Extent Report'
                ])
            }
        }
    }
}